// "use client";
import AuthProvider from './context/AuthProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Truck Dispatch App',
  description: 'Generated by Axfu',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}><AuthProvider>{children}</AuthProvider></body>
    </html>
  )
}
